### ISSUE TITLE
vel_pkg: Cannot locate rosdep definition for [gepmetry_msgs]

### ISSUE THREAD

**Issue by yspjack** [sebuaa2020/Documents#2]
There is a typo in vel_pkg/package.xml
https://github.com/sebuaa2020/Documents/blob/d5160b497e0357012ea6c2fda161066c411b76c9/demo/vel_pkg/package.xml#L52

https://github.com/sebuaa2020/Documents/blob/d5160b497e0357012ea6c2fda161066c411b76c9/demo/vel_pkg/package.xml#L54

https://github.com/sebuaa2020/Documents/blob/d5160b497e0357012ea6c2fda161066c411b76c9/demo/vel_pkg/package.xml#L56

**Comment by yspjack** [comment]
Fixed. Commit: 804f032eb4cdc0a2ad852987fa466af003e6310f

**Comment by sebuaa2020** [comment]
包名有误，现在已经修正
